version: '3.8'

services:
  nginx:
    depends_on:
      - php
    image: nginx:alpine
    container_name: app-nginx
    ports:
      - "${NGINX_HTTP_PORT:-8080}:80"
      - "${NGINX_HTTPS_PORT:-8443}:443"
    volumes:
      - ./:/var/www:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network

  php:
    depends_on:
      - db
    image: php:8.1-fpm
    container_name: app-php
    volumes:
      - ./:/var/www
    networks:
      - app_network

  db:
    image: mysql:5.6.47
    platform: linux/amd64
    container_name: app-db
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./etc/infrastructure/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./etc/database/base.sql:/docker-entrypoint-initdb.d/base.sql:ro
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-appdb}
      MYSQL_USER: ${DB_USER:-app}
      MYSQL_PASSWORD: ${DB_PASS:-app_pass}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    driver: local
    name: project_db_data